import Foundation


public struct QueryResponse: Codable {
    
    public let rows: [Row]
    
    public init(rows: [Row]) {
        self.rows = rows
    }
    
}


public struct WriteResponse: Codable {
    
    public let numberOfAffectedRows: Int
    public let autoGeneratedKeys: [String]
    
    public init(numberOfAffectedRows: Int, autoGeneratedKeys: [String]) {
        self.numberOfAffectedRows = numberOfAffectedRows
        self.autoGeneratedKeys = autoGeneratedKeys
    }
    
}

public struct BatchWriteResponse: Codable {
    
    public let numberOfAffectedRows: [Int]
    
}

public struct ServerError: Codable, Error {
    
    public let error: String
    
}
